title: Eat Sleep Skate
title_short: ESS Bali
title_long: ESS Bali • Eat Sleep Skate
email: essbali2015@gmail.com
telephone: +62 361 4720185
handphone: +62 818 05620365
whatsapp: +62 818 05620365
address:  Jl. Sedap Malam, Gg. Kwangen 13, Banjar Bhuana Anyar, Sumerta Kelod, Denpasar Timur, Bali 80237
short_address: Jl. Sedap Malam, Gg. Kwangen 13, Banjar Bhuana Anyar, Sanur.
description: > # this means to ignore newlines until "baseurl:"
  Wooden chalets, swimming pool, restaurant, and one of the most fun skateboarding bowls in Indonesia. Located 10 minutes from Sanur beach. We designed it all ourselves in harmony with it’s peaceful green environment. Open on weekends 4pm to 10pm. Reserved to our guest for the rest of the time. A place where you can Eat Sleep and Skate.
baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://essbali.com"
url: "https://toybreaker.github.io/ess/"
repository: toybreaker/ess
instagram: https://www.instagram.com/eatsleepskatebali
instagram_tag: https://www.instagram.com/explore/tags/essbali
facebook: https://www.facebook.com/essbali
twitter: https://twitter.com/essbali
booking: http://booking.com/e682abb837ed8f61f
tripadvisor: http://www.tripadvisor.com/Hotel_Review-g297700-d7732966-Reviews-Eat_Sleep_Skate-Sanur_Denpasar_Bali.html
google:
  youtube: https://www.youtube.com/channel/UCptyllNdDP7Cx_3wHwKU8-Q
  analytics: UA-89049941-1
  maps: https://goo.gl/maps/pPpJSdKjMsn
  verification:
# instuff
userId: '2946518376'
clientId: 'ec2404a26b26481c93a9b8bd5f24363e'
accessToken: '2946518376.ec2404a.37bf765fa57343a380feeb950c0d31b6'

# Build settings
markdown: kramdown
gems:
 - jekyll-mentions
 - jekyll-redirect-from
 - jekyll-sitemap
 - jekyll-feed
